source 'https://rubygems.org'
gem 'rails', '4.0.2'
gem 'pg' #for heroku deployment
gem 'mysql2'
gem 'haml'
gem 'bootstrap-sass'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'redcarpet'
gem 'shoppe', '~> 0.0.20'
gem 'shoppe-stripe', :require => 'shoppe/stripe'
gem 'xeroizer'